site_name: db-diagram
site_url: https://db-diagram.enorganic.org
repo_url: https://github.com/enorganic/db-diagram/
edit_uri: blob/main/docs/
nav:
- Introduction: 'index.md'
- CLI Reference: 'cli.md'
- API Reference: 'api.md'
- Examples:
    - Overview: 'examples/index.md'
    - Depth=1:
      - ab_*: 'examples/airflow/depth=1/ab-diagrams.md'
      - dag_*: 'examples/airflow/depth=1/dag-diagrams.md'
      - asset_*: 'examples/airflow/depth=1/asset-diagrams.md'
      - task_*: 'examples/airflow/depth=1/task-diagrams.md'
      - other: 'examples/airflow/depth=1/other-diagrams.md'
      - (all): 'examples/airflow/depth=1/diagrams.md'
    - Depth=2:
      - ab_*: 'examples/airflow/depth=2/ab-diagrams.md'
      - dag_*: 'examples/airflow/depth=2/dag-diagrams.md'
      - asset_*: 'examples/airflow/depth=2/asset-diagrams.md'
      - task_*: 'examples/airflow/depth=2/task-diagrams.md'
      - other: 'examples/airflow/depth=2/other-diagrams.md'
      - (all): 'examples/airflow/depth=2/diagrams.md'
    - Depth=3:
      - ab_*: 'examples/airflow/depth=3/ab-diagrams.md'
      - dag_*: 'examples/airflow/depth=3/dag-diagrams.md'
      - asset_*: 'examples/airflow/depth=3/asset-diagrams.md'
      - task_*: 'examples/airflow/depth=3/task-diagrams.md'
      - other: 'examples/airflow/depth=3/other-diagrams.md'
      - (all): 'examples/airflow/depth=3/diagrams.md'
    - "Depth=1 (SVG)": 'examples/airflow/depth=1/diagrams-svg.md'
    - "Depth=2 (SVG)": 'examples/airflow/depth=2/diagrams-svg.md'
    - "Depth=3 (SVG)": 'examples/airflow/depth=3/diagrams-svg.md'
- Contributing: 'contributing.md'
- Report a Bug: https://github.com/enorganic/db-diagram/issues/new
theme:
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
plugins:
  - search
  - autorefs
  - mermaid2:
      arguments:
        securityLevel: 'loose'
        theme: |
          ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            inherited_members: true
            heading_level: 1
            separate_signature: true
            annotations_path: full
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - assets/stylesheets/style.css
extra_javascript:
  - assets/javascripts/extra.js
